export const JUTSUS = {
  HEAL: {
    id: 'HEAL',
    name: 'Shōsen Jutsu',
    subtitle: 'Palmo Mistico',
    character: 'Sakura · Tsunade',
    sequence: ['Pecora'],
    effectType: 'heal',
    color: '#10B981',
    glowColor: 'rgba(16,185,129,0.7)',
    kanji: '掌仙術',
    imageId: 'sakura_heal',
    damage: 0,
    minXp: 0
  },
  BUNSHIN: {
    id: 'BUNSHIN',
    name: 'Bunshin no Jutsu',
    subtitle: 'Moltiplicazione del Corpo',
    character: 'Naruto',
    sequence: ['Croce'],
    effectType: 'clone',
    color: '#C084FC',
    glowColor: 'rgba(192,132,252,0.6)',
    kanji: '分身の術',
    imageId: 'naruto_moltiplicazione',
    damage: 20,
    minXp: 0
  },
  KATON: {
    id: 'KATON',
    name: 'Katon · Gōkakyū',
    subtitle: 'Grande Sfera di Fuoco',
    character: 'Sasuke · Clan Uchiha',
    sequence: ['Serpente', 'Cavallo', 'Tigre'],
    effectType: 'fire',
    color: '#EF4444',
    glowColor: 'rgba(239,68,68,0.6)',
    kanji: '火遁・豪火球の術',
    imageId: 'sasuke_palla_di_fuoco',
    damage: 35,
    minXp: 0
  },
  RASENGAN: {
    id: 'RASENGAN',
    name: 'Rasengan',
    subtitle: 'Sfera Rotante',
    character: 'Naruto',
    sequence: ['Rana', 'Cinghiale', 'Ariete'],
    effectType: 'wind',
    color: '#F97316',
    glowColor: 'rgba(249,115,22,0.6)',
    kanji: '螺旋丸',
    imageId: 'naruto_rasengan',
    damage: 40,
    minXp: 0
  },
  CHIDORI: {
    id: 'CHIDORI',
    name: 'Chidori',
    subtitle: 'Mille Falchi',
    character: 'Sasuke · Kakashi',
    sequence: ['Bue', 'Lepre', 'Scimmia'],
    effectType: 'lightning',
    color: '#38BDF8',
    glowColor: 'rgba(56,189,248,0.6)',
    kanji: '千鳥',
    imageId: 'kakashi_mille_falchi',
    damage: 45,
    minXp: 600
  },
  KAGE_BUNSHIN: {
    id: 'KAGE_BUNSHIN',
    name: 'Kage Bunshin',
    subtitle: "Cloni d'Ombra",
    character: 'Naruto',
    sequence: ['Serpente', 'Ariete', 'Cane'],
    effectType: 'shadow',
    color: '#A855F7',
    glowColor: 'rgba(168,85,247,0.6)',
    kanji: '影分身の術',
    imageId: 'naruto_moltiplicazione',
    damage: 50,
    minXp: 1200
  },
  KUCHIYOSE: {
    id: 'KUCHIYOSE',
    name: 'Kuchiyose no Jutsu',
    subtitle: 'Tecnica del Richiamo',
    character: 'Jiraiya · Rospi del Monte Myoboku',
    sequence: ['Cinghiale', 'Cane', 'Uccello', 'Scimmia', 'Pecora'],
    effectType: 'summon',
    color: '#FCD34D',
    glowColor: 'rgba(252,211,77,0.6)',
    kanji: '口寄せの術',
    imageId: 'gamapunta',
    damage: 65,
    minXp: 2500
  },
  SUITON: {
    id: 'SUITON',
    name: 'Suiton · Suiryūdan',
    subtitle: 'Drago Acquatico',
    character: 'Kisame · Clan Hoshigaki',
    sequence: ['Bue', 'Scimmia', 'Uccello', 'Pecora', 'Cane', 'Tigre'],
    effectType: 'water',
    color: '#3B82F6',
    glowColor: 'rgba(59,130,246,0.6)',
    kanji: '水遁・水龍弾の術',
    imageId: 'kisame_drago_acquatico',
    damage: 80,
    minXp: 4500
  },
  TSUKUYOMI: {
    id: 'TSUKUYOMI',
    name: 'Mangekyō Sharingan',
    subtitle: "Il Dōjutsu Supremo degli Uchiha",
    character: 'Itachi · Clan Uchiha',
    sequence: ['Tigre', 'Bue', 'Serpente'],
    effectType: 'sharingan',
    color: '#DC2626',
    glowColor: 'rgba(220,38,38,0.8)',
    kanji: '万華鏡写輪眼',
    imageId: 'itachi_susanoo',
    damage: 100,
    minXp: 6000
  },
  SUSANOO: {
    id: 'SUSANOO',
    name: 'Susanoo',
    subtitle: 'Armatura Spettrale',
    character: 'Itachi · Clan Uchiha',
    sequence: ['Tigre', 'Cinghiale', 'Serpente', 'Ariete'],
    effectType: 'susanoo',
    color: '#A855F7',
    glowColor: 'rgba(168,85,247,0.8)',
    kanji: '須佐能乎',
    imageId: 'itachi_susanoo',
    damage: 125,
    minXp: 8000
  },
  SHINRA_TENSEI: {
    id: 'SHINRA_TENSEI',
    name: 'Shinra Tensei',
    subtitle: 'Sottomissione Celestiale',
    character: 'Pain · Sei Sentieri',
    sequence: ['Ariete', 'Serpente', 'Tigre', 'Uccello'],
    effectType: 'push',
    color: '#FFFFFF',
    glowColor: 'rgba(255,255,255,0.8)',
    kanji: '神羅天征',
    imageId: 'pain_shinratensei',
    damage: 150,
    minXp: 12000
  }
};

// All unique seals needed across all jutsu
export const SEALS_LIST = [...new Set(
  Object.values(JUTSUS).flatMap(j => j.sequence)
)];

export const BOSSES = {
  zabusa:     { name: 'Zabuza',     maxHp: 80,  minXp: 0,     specialAttack: 'Taglio della Mannaia',    specialDamage: 15,  xpReward: 100,  weakness: 'lightning' },
  deidara:    { name: 'Deidara',    maxHp: 120, minXp: 400,   specialAttack: 'C4 Karura',               specialDamage: 25,  xpReward: 150,  weakness: 'lightning' },
  orochimaru: { name: 'Orochimaru', maxHp: 140, minXp: 1000,  specialAttack: 'Spada Kusanagi',          specialDamage: 35,  xpReward: 200,  weakness: 'susanoo'   },
  kabuto:     { name: 'Kabuto',     maxHp: 160, minXp: 1800,  specialAttack: 'Edo Tensei',              specialDamage: 40,  xpReward: 250,  weakness: 'sharingan' },
  danzo:      { name: 'Danzō',      maxHp: 180, minXp: 2800,  specialAttack: 'Izanagi',                 specialDamage: 45,  xpReward: 300,  weakness: 'susanoo'   },
  itachi:     { name: 'Itachi',     maxHp: 200, minXp: 4000,  specialAttack: 'Amaterasu',               specialDamage: 60,  xpReward: 400,  weakness: 'lightning' },
  sasuke:     { name: 'Sasuke',     maxHp: 220, minXp: 5500,  specialAttack: 'Freccia di Indra',        specialDamage: 70,  xpReward: 500,  weakness: 'wind'      },
  pain:       { name: 'Pain',       maxHp: 250, minXp: 7500,  specialAttack: 'Shinra Tensei',           specialDamage: 90,  xpReward: 600,  weakness: 'summon'    },
  obito:      { name: 'Obito',      maxHp: 280, minXp: 10000, specialAttack: 'Kamui',                   specialDamage: 110, xpReward: 700,  weakness: 'water'     },
  madara:     { name: 'Madara',     maxHp: 320, minXp: 13000, specialAttack: 'Meteora Celeste',         specialDamage: 130, xpReward: 800,  weakness: 'shadow'    },
  zetsu:      { name: 'Zetsu Nero', maxHp: 360, minXp: 16000, specialAttack: 'Tradimento Oscuro',       specialDamage: 150, xpReward: 900,  weakness: 'push'      },
  kaguya:     { name: 'Kaguya',     maxHp: 400, minXp: 19000, specialAttack: 'Cenere Polverizzatrice',  specialDamage: 180, xpReward: 1000, weakness: 'push'      },
};
