export const JUTSUS = {
  BUNSHIN: {
    id: 'BUNSHIN',
    name: 'Bunshin no Jutsu',
    subtitle: 'Moltiplicazione del Corpo',
    character: 'Naruto',
    sequence: ['Croce'],
    effectType: 'clone',
    color: '#C084FC',
    glowColor: 'rgba(192,132,252,0.6)',
    kanji: '分身',
    imageId: 'naruto_moltiplicazione',
  },
  CHIDORI: {
    id: 'CHIDORI',
    name: 'Chidori',
    subtitle: 'Mille Falchi',
    character: 'Sasuke · Kakashi',
    sequence: ['Bue', 'Lepre', 'Scimmia'],
    effectType: 'lightning',
    color: '#38BDF8',
    glowColor: 'rgba(56,189,248,0.6)',
    kanji: '千鳥',
    imageId: 'kakashi_mille_falchi',
  },
  RASENGAN: {
    id: 'RASENGAN',
    name: 'Rasengan',
    subtitle: 'Sfera Rotante',
    character: 'Naruto',
    sequence: ['Rana', 'Cinghiale', 'Ariete'],
    effectType: 'wind',
    color: '#F97316',
    glowColor: 'rgba(249,115,22,0.6)',
    kanji: '螺旋丸',
    imageId: 'naruto_rasengan',
  },
  KATON: {
    id: 'KATON',
    name: 'Katon · Gōkakyū',
    subtitle: 'Grande Sfera di Fuoco',
    character: 'Sasuke · Clan Uchiha',
    sequence: ['Serpente', 'Cavallo', 'Tigre'],
    effectType: 'fire',
    color: '#EF4444',
    glowColor: 'rgba(239,68,68,0.6)',
    kanji: '火遁',
    imageId: 'sasuke_palla_di_fuoco',
  },
  KAGE_BUNSHIN: {
    id: 'KAGE_BUNSHIN',
    name: 'Kage Bunshin',
    subtitle: "Cloni d'Ombra",
    character: 'Naruto',
    sequence: ['Serpente', 'Ariete', 'Cane'],
    effectType: 'shadow',
    color: '#A855F7',
    glowColor: 'rgba(168,85,247,0.6)',
    kanji: '影分身',
    imageId: 'naruto_moltiplicazione',
  },
  KUCHIYOSE: {
    id: 'KUCHIYOSE',
    name: 'Kuchiyose no Jutsu',
    subtitle: 'Tecnica del Richiamo',
    character: 'Naruto · Jiraiya',
    sequence: ['Cinghiale', 'Cane', 'Uccello', 'Scimmia', 'Ariete'],
    effectType: 'summon',
    color: '#10B981',
    glowColor: 'rgba(16,185,129,0.6)',
    kanji: '口寄せの術',
    imageId: 'jiraya',
  },
};

// All unique seals needed across all jutsu
export const SEALS_LIST = [...new Set(
  Object.values(JUTSUS).flatMap(j => j.sequence)
)];
